// frontend/src/components/month/MonthTableHead.tsx
import { For } from "solid-js";

const weekDays = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"] as const;

export default function MonthTableHead() {
  return (
    <tr>
      <For each={weekDays}>
        {(name) => (
          <td class="w-10 h-10 bg-table-border border-2 border-table-border text-center font-medium">
            {name}
          </td>
        )}
      </For>
    </tr>
  );
}

// frontend/src/lib/components/month/MonthTableHead.svelte
<script lang="ts">
  export const prerender = true;

  const weekDays = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"] as const;
</script>

<thead>
  <tr>
    {#each weekDays as weekDay}
      <td
        class="h-10 w-10 border-2 border-table-border bg-table-border text-center font-medium"
      >
        {weekDay}
      </td>
    {/each}
  </tr>
</thead>
