// frontend/src/lib/components/month/MonthTableBody.svelte
<script lang="ts">
	import { Day, DayType, type Event } from '$lib/types';
	import DayInfo from '../day/DayInfo.svelte';
	import DayMenu from '../day/DayMenu.svelte';

	type Props = {
		days: Day[][];
	};

	const { days }: Props = $props();

	let selectedDay = $state<Day | null>(null);
	let selectedDayEvents = $state<Event[] | null>(null);
	$effect(() => {
		if (selectedDay !== null) {
			Day.getEvents(selectedDay.day_id).then((events) => (selectedDayEvents = events));
		}
	});

	function onCreateEvent(events: Partial<Event>[]) {}
</script>

{#if selectedDay !== null && selectedDayEvents !== null}
	<DayMenu
		day={selectedDay}
		events={selectedDayEvents}
		onClose={() => (selectedDay = null)}
		{onCreateEvent}
	/>
{/if}

<tbody>
	{#each days as week}
		<tr>
			{#each week as day}
				<td
					onclick={() => {
						if (day.day_type !== DayType.Uneditable) {
							selectedDay = day;
						}
					}}
					class={{
						'day day-uneditable': day.day_type === DayType.Uneditable,
						'day day-undefined': day.day_type === DayType.Undefined,
						'day day-busy': day.day_type === DayType.Busy,
						'day day-free': day.day_type === DayType.Free
					}}
				>
					<DayInfo dayNumber={day.day_number} eventsCount={day.events?.length} />
				</td>
			{/each}
		</tr>
	{/each}
</tbody>

// frontend/src/components/month/MonthTableBody.tsx
import DayInfo from "$components/day/DayInfo";
import DayMenu from "$components/day/DayMenu";
import { useCurrentMonth } from "$lib/context/CurrentMonthContext";
import { Day, DayType } from "$lib/types/day";
import { Event } from "$lib/types/event";
import { createResource, createSignal, For, Show } from "solid-js";

export default function MonthTableBody() {
  const { days } = useCurrentMonth();

  const [selectedDay, setSelectedDay] = createSignal<Day | null>(null);

  const [selectedDayEvents] = createResource(
    () => selectedDay()?.day_id,
    Day.getEvents
  );

  const onCreateEvent = (events: Partial<Event>[]) => {
    alert("New events: " + JSON.stringify(events));
  };

  return (
    <>
      <Show when={selectedDay() && selectedDayEvents()}>
        <DayMenu
          day={selectedDay()!}
          events={selectedDayEvents()!}
          onClose={() => setSelectedDay(null)}
          onCreateEvent={onCreateEvent}
        />
      </Show>
      <tbody>
        <For each={days()}>
          {(week) => (
            <tr>
              <For each={week}>
                {(day) => (
                  <td
                    onClick={() =>
                      setSelectedDay(
                        day.day_type === DayType.Uneditable ? null : day
                      )
                    }
                    classList={{
                      "day day-uneditable": day.day_type === DayType.Uneditable,
                      "day day-undefined": day.day_type === DayType.Undefined,
                      "day day-busy": day.day_type === DayType.Busy,
                      "day day-free": day.day_type === DayType.Free,
                    }}
                  >
                    <DayInfo
                      dayNumber={day.day_number}
                      eventsCount={day.events.length}
                    />
                  </td>
                )}
              </For>
            </tr>
          )}
        </For>
      </tbody>
    </>
  );
}
